apiVersion: v2
name: nexus
description: Sonatype Nexus is an open source repository manager
type: application
appVersion: "3.30.0"
version: "1.0.7"
home: https://github.com/curie-data-factory/helm-charts/tree/master/charts/nexus
icon: https://help.sonatype.com/docs/files/331022/34537964/3/1564671303641/NexusRepo_Icon.png
sources:
  - https://github.com/sonatype/nexus-public
maintainers:
  - name: armandleopold
    email: armand.leopold@curie.fr
kubeVersion: ">= 1.14.0-0"
keywords:
  - nexus
  - registry
annotations:
  artifacthub.io/images: |
    - name: nexus
      image: sonatype/nexus3:3.30.0
