apiVersion: v2
name: job-orchestrator
description: Helm Chart for Job Orchestrator, Help Manages jobs by connecting Gitlab Runners / Nexus Ressources with Kubernetes.
type: application
appVersion: 1.3.2
version: 1.9.13
home: https://github.com/curie-data-factory/helm-charts/tree/master/charts/job-orchestrator
icon: https://i.ibb.co/2sGpDKj/favicon.png
sources:
  - https://github.com/curie-data-factory/job-orchestrator
maintainers:
  - name: armandleopold
    email: armand.leopold@curie.fr
kubeVersion: ">= 1.14.0-0"
keywords:
  - kubernetes
  - gitlab
  - devops
  - docker
  - nexus
